const ADD_POST_SUCCESS = 'posts/ADD_POST_SUCCESS';
const GET_ALL_POSTS_SUCCESS = 'posts/GET_ALL_POSTS_SUCCESS';
const FETCH_REQUEST = 'posts/FETCH_REQUEST';
const FETCH_ERROR = 'posts/FETCH_ERROR';

export default {
    ADD_POST_SUCCESS,
    GET_ALL_POSTS_SUCCESS,
    FETCH_REQUEST,
    FETCH_ERROR,
};
